version: '3.7'

networks:
    net_1:
        driver: bridge
        ipam:
            config:
                - subnet: 172.32.0.0/12
                  gateway: 172.32.0.1

volumes:
    data-volume:
        name: my-app-data

services:
    keycloak:
        image: quay.io/keycloak/keycloak:17.0.0
        restart: always
        ports:
            - "8080:8080"
        # expose:
        #     - "8080"
        #network_mode: "host"
        networks:
            # - net_1
            net_1:
                ipv4_address: 172.32.0.3
        # volumes:
        #     - data-volume:/var/lib/keycloak
        environment:
            KEYCLOAK_ADMIN: admin
            KEYCLOAK_ADMIN_PASSWORD: admin
        command: start-dev
    database:
        image: postgres:12
        restart: always
        ports:
            - "5432:5432"
        # expose:
        #     - "5432"
        #network_mode: "host"
        networks:
            # - net_1
            net_1:
                ipv4_address: 172.32.0.2
        environment:
            POSTGRES_USER: coursework
            POSTGRES_PASSWORD: coursework
            POSTGRES_DB: coursework
    backend:
        image: quarkus/coursework-jvm
        restart: always
        ports:
            - "8081:8081"
        # expose:
        #     - "8080"
        #network_mode: "host"
        networks:
            # - net_1
            net_1:
                ipv4_address: 172.32.0.4
        depends_on:
            keycloak:
                condition: service_started
            database:
                condition: service_started
    frontend:
        image: my-work
        restart: always
        ports:
            - "3000:3000"
        # expose:
        #     - "80"
        #     - "8080"
        #     - "3000"
        #network_mode: "host"
        networks:
            # - net_1
            net_1:
                ipv4_address: 172.32.0.5
        command: npm run serve
        depends_on:
            backend:
                condition: service_started
